### ISSUE TITLE
Unable to load application: RuntimeError: Devise.secret_key was not set.

### ISSUE THREAD

**Issue by vegeta03** [andregr15/OneBitForms#1]
Hi @andregr15 ,

  I am new to ruby, wanted to try out the Angular frontend but it requires this backend (i think).
  
  Could you help, these are the steps i followed:
  - installed ruby with ruby installer2 of version 2.5.5
  - did `gem update --system`
  - changed ruby version in gemfile to 2.5.5
  - `bundle install`
  - `bundle exec puma -C config/puma.rb`

then this error occurred:

$ bundle exec puma -C config/puma.rb
*** SIGUSR2 not implemented, signal based restart unavailable!
*** SIGUSR1 not implemented, signal based restart unavailable!
*** SIGHUP not implemented, signal based logs reopening unavailable!
Puma starting in single mode...
* Version 3.12.0 (ruby 2.5.5-p157), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
! Unable to load application: RuntimeError: Devise.secret_key was not set. Please add the following to your Devise initializer:

  config.secret_key = '3efd79ed4a9e08a7ad1d6e5e90d53b780c4fd8e6c6de6af1b925bc23d298d9c783b7025f30981075f0b53ee8807abc3604fd9fc4977717115709ce6e9184d144'

Please ensure you restarted your application after installing Devise or setting the key.
Traceback (most recent call last):
        67: from C:/Ruby25-x64/bin/puma:23:in `<main>'
        66: from C:/Ruby25-x64/bin/puma:23:in `load'
        65: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/puma-3.12.0/bin/puma:10:in `<top (required)>'
        64: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/cli.rb:78:in `run'
        63: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/launcher.rb:184:in `run'
        62: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/single.rb:96:in `run'
        61: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/runner.rb:145:in `load_and_bind'
        60: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:243:in `app'
        59: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:318:in `load_rackup'
        58: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
        57: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
        56: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
        55: from config.ru:in `<main>'
        54: from config.ru:in `new'
        53: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
        52: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
        51: from config.ru:3:in `block in <main>'
        50: from config.ru:3:in `require_relative'
        49: from D:/Shyam/Workspace/hacking/OneBitForms/config/environment.rb:5:in `<top (required)>'
        48: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/application.rb:361:in `initialize!'
        47: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:60:in `run_initializers'
        46: from C:/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
        45: from C:/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
        44: from C:/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
        43: from C:/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:347:in `call'
        42: from C:/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:347:in `each'
        41: from C:/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
        40: from C:/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
        39: from C:/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        38: from C:/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
        37: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
        36: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `run'
        35: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `instance_exec'
        34: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/application/finisher.rb:130:in `block in <module:Finisher>'
        33: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/application/routes_reloader.rb:10:in `execute'
        32: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/file_update_checker.rb:83:in `execute'
        31: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/application/routes_reloader.rb:30:in `block in updater'
        30: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/application/routes_reloader.rb:20:in `reload!'
        29: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/application/routes_reloader.rb:41:in `load_paths'
        28: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/application/routes_reloader.rb:41:in `each'
        27: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/application/routes_reloader.rb:41:in `block in load_paths'
        26: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
        25: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
        24: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `block in load'
        23: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
        22: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
        21: from D:/Shyam/Workspace/hacking/OneBitForms/config/routes.rb:1:in `<top (required)>'
        20: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:414:in `draw'
        19: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
        18: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
        17: from D:/Shyam/Workspace/hacking/OneBitForms/config/routes.rb:3:in `block in <top (required)>'
        16: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/mapper.rb:1559:in `namespace'
        15: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/mapper.rb:947:in `namespace'
        14: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/mapper.rb:1833:in `path_scope'
        13: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/mapper.rb:948:in `block in namespace'
        12: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/mapper.rb:879:in `scope'
        11: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/mapper.rb:948:in `block (2 levels) in namespace'
        10: from D:/Shyam/Workspace/hacking/OneBitForms/config/routes.rb:4:in `block (2 levels) in <top (required)>'
         9: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/mapper.rb:1559:in `namespace'
         8: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/mapper.rb:947:in `namespace'
         7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/mapper.rb:1833:in `path_scope'
         6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/mapper.rb:948:in `block in namespace'
         5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/mapper.rb:879:in `scope'
         4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/mapper.rb:948:in `block (2 levels) in namespace'
         3: from D:/Shyam/Workspace/hacking/OneBitForms/config/routes.rb:5:in `block (3 levels) in <top (required)>'
         2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/devise_token_auth-0.2.0/lib/devise_token_auth/rails/routes.rb:30:in `mount_devise_token_auth_for'
         1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/devise-4.4.3/lib/devise/rails/routes.rb:228:in `devise_for'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/devise-4.4.3/lib/devise/rails/routes.rb:500:in `raise_no_secret_key': Devise.secret_key was not set. Please add the following to your Devise initializer: (RuntimeError)

  config.secret_key = '3efd79ed4a9e08a7ad1d6e5e90d53b780c4fd8e6c6de6af1b925bc23d298d9c783b7025f30981075f0b53ee8807abc3604fd9fc4977717115709ce6e9184d144'

Please ensure you restarted your application after installing Devise or setting the key.

Thanks,
Shyam Sreenivasan

**Comment by andregr15** [comment]
Greetings,

I made some changes on de code, please do a git pull and try again.
If you have any trouble feel free to let me know.

Thanks,

André Rodrigues

**Comment by vegeta03** [comment]
Thank you.

Shyam S
